geometry: 
  fuel_radius: [0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.40, 0.41, 0.42, 0.43, 0.44, 0.45, 0.46]
  clad_thickness: 0.06
  gap: 0.01
  pitch: 1.26

settings:
  particles: 4000
  batches: 30
  inactive: 5